/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/translate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["translate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        TranslateRequest: {
            text: string;
            /** @enum {string} */
            direction: "PT_TO_BR" | "BR_TO_PT";
            context?: string;
        };
        TranslateResponse: {
            input?: string;
            translations?: components["schemas"]["TranslationItem"][];
            fullTranslation?: string;
            warnings?: string[];
            status?: string;
            suggestions?: string[];
            contributeUrl?: string;
        };
        TranslationItem: {
            source?: string;
            target?: string;
            alternatives?: string[];
            register?: string;
            falseFriend?: boolean;
            note?: string;
            example?: string;
            /** Format: double */
            confidence?: number;
            resolvedBy?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    translate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TranslateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TranslateResponse"];
                };
            };
        };
    };
}
